# Generated by Django 4.2.3 on 2023-07-13 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_brand_details_brand_source_company_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='ranking',
            new_name='classification',
        ),
    ]
