# Generated by Django 4.2.3 on 2023-07-14 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='companies.company'),
        ),
    ]
