# Generated by Django 4.2.3 on 2023-07-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_parent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default=None, max_length=200, null=True, upload_to=''),
        ),
    ]
