# Generated by Django 4.2.3 on 2023-07-25 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholder',
            name='share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
